# -*- coding: utf-8 -*-
"""Data Visualization Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/120PaGd1ZMLaORhQmwftZ73NWbRrb2jLD
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
from numpy.random import randn, randint, uniform, sample
import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline

"""Question 1 - plot a line plot between a and b:
a=np.arange(40,50)
b=np.arange(50,60)
"""

a=np.arange(40,50)
b=np.arange(50,60)
plt.plot(a,b,'go--', linewidth=1, markersize=1)
plt.title('Line Plot')
plt.xlabel('x-axis')
plt.ylabel('y-axis')

"""Question 2 - 
Plot a line plot showing the sales trend in company 1 and 2:

days = [1,2,3,4,5,6,7] #days of d week
sales_1 = [160,150,140,145,175,165,180] #sales of company1
sales_2 = [70,90,160,150,140,145,175]  #sales of company2

"""

days = [1,2,3,4,5,6,7]
sales_1 = [160,150,140,145,175,165,180]
sales_2 = [70,90,160,150,140,145,175]

plt.plot(days,sales_1, color = 'purple')
plt.plot(days,sales_2, color = 'orange')
plt.title('trend', fontsize = 12, color = 'black')
plt.xlabel('Days of week')
plt.ylabel('Sales price')
plt.show

"""Question 3 - Create a 3 by 3 subplots:
multiple plots
x = [1,2,3,4]
y1 = [4,3,2,1]
y2 = [10,20,30,40]
y3 = [40,30,20,10]
y4 = [1,2,1,2]
y5 = [40,70,90,70]

"""

x = [1,2,3,4] 
 y1 = [4,3,2,1] 
 y2 = [10,20,30,40] 
 y3 = [40,30,20,10] 
 y4 = [1,2,1,2] 
 y5 = [40,70,90,70]

plt.figure(figsize = (5,5))
plt.subplot(3,3,1)
plt.plot(x,y1)
plt.xlabel('X-axis', color='blue')
plt.ylabel('Y-axis', color='blue')
plt.title('subplot1')
plt.show

plt.figure(figsize = (5,5))
plt.subplot(3,3,1)
plt.plot(x,y2)
plt.xlabel('X-axis', color='blue')
plt.ylabel('Y-axis', color='blue')
plt.title('subplot1')

plt.figure(figsize = (5,5))
plt.subplot(3,3,1)
plt.plot(x,y3)
plt.xlabel('X-axis', color='blue')
plt.ylabel('Y-axis', color='blue')
plt.title('subplot1')

plt.figure(figsize = (5,5))
plt.subplot(3,3,1)
plt.plot(x,y4)
plt.xlabel('X-axis', color='blue')
plt.ylabel('Y-axis', color='blue')
plt.title('subplot1')

plt.figure(figsize = (5,5))
plt.subplot(3,3,1)
plt.plot(x,y5)
plt.xlabel('X-axis', color='blue')
plt.ylabel('Y-axis', color='blue')
plt.title('subplot1')
plt.show